<?php

namespace App\Command;

use App\Services\AnonymizationUser;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class AnonymizUsers extends Command
{
    protected static $defaultName = 'app:anonymizUsers';
    private $anonymiz;

    public function __construct(AnonymizationUser $anonymiz)
    {
        try {
            $this->anonymiz = $anonymiz->anonymizUser();
        } catch (\Exception $e) {
        }

        parent::__construct();
    }

    protected function configure()
    {
        $this->setDescription('Anonymiz user after 3 years inactivity');
        $this->setHelp('anonymise les utilisateurs inactifs depuis plus de 3 ans.');

        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->anonymiz;
        $output->writeln([
            '=======================',
            'anonymisation effectuée.',
            '======================='
        ]);

        return 0;
    }

}