<?php


namespace App\Form;

use App\Entity\RateCard;
use App\Entity\Simulation;
use App\Repository\RateCardRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SimulationType extends AbstractType
{
    /**
     * @var RateCardRepository
     */
    private $repository;

    /**
     * @param RateCardRepository $repository
     */
    public function __construct(RateCardRepository $repository)
    {
        $this->repository = $repository;
    }

    public function buildForm(
        FormBuilderInterface $builder,
        array $options
    )
    {
        $builder
            ->add('quantity')
            ->add('country',
                ChoiceType::class, [
                'choices' => [
                    'France'     => 'France',
                    'Angleterre' => 'Angleterre'
                ],
                'mapped' => false,
            ])
            ->add('prestation',
                ChoiceType::class, [
                    'choices' => [
                        'SILVER'     => 'SILVER',
                        'GOLD' => 'GOLD'
                    ],
                'expanded' => true,
                'multiple' => false,
                'required' => true,
                'mapped' => false,
            ])
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Simulation::class
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}